# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
    # Q == quick to current path
    { on = "q", run = "quit --no-cwd-file", desc = "Exit the process without writing cwd-file" },
    { on = "Q", run = "quit", desc = "Exit the process" },

    # compress
    { on = [
        "<C-p>",
        "a",
    ], run = "plugin compress", desc = "Archive selected files" },

    # chmod
    { on = [
        "c",
        "m",
    ], run = "plugin chmod", desc = "Chmod on selected files" },

    # diff
    { on = [
        "<C-p>",
        "d",
    ], run = "plugin diff", desc = "Diff the selected with the hovered file" },

    # smart-enter
    { on = "<Enter>", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
]

[input]
prepend_keymap = [
    # Close input by once Esc press
    { on = "<Esc>", run = "close", desc = "Cancel input" },
]
